/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClickEventService } from "../clickEvent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClickEventCreateInput } from "./ClickEventCreateInput";
import { ClickEvent } from "./ClickEvent";
import { ClickEventFindManyArgs } from "./ClickEventFindManyArgs";
import { ClickEventWhereUniqueInput } from "./ClickEventWhereUniqueInput";
import { ClickEventUpdateInput } from "./ClickEventUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClickEventControllerBase {
  constructor(
    protected readonly service: ClickEventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ClickEvent })
  @nestAccessControl.UseRoles({
    resource: "ClickEvent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createClickEvent(
    @common.Body() data: ClickEventCreateInput
  ): Promise<ClickEvent> {
    return await this.service.createClickEvent({
      data: {
        ...data,

        gameSession: data.gameSession
          ? {
              connect: data.gameSession,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        clickTime: true,

        gameSession: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ClickEvent] })
  @ApiNestedQuery(ClickEventFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClickEvent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async clickEvents(@common.Req() request: Request): Promise<ClickEvent[]> {
    const args = plainToClass(ClickEventFindManyArgs, request.query);
    return this.service.clickEvents({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        clickTime: true,

        gameSession: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ClickEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClickEvent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async clickEvent(
    @common.Param() params: ClickEventWhereUniqueInput
  ): Promise<ClickEvent | null> {
    const result = await this.service.clickEvent({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        clickTime: true,

        gameSession: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ClickEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClickEvent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateClickEvent(
    @common.Param() params: ClickEventWhereUniqueInput,
    @common.Body() data: ClickEventUpdateInput
  ): Promise<ClickEvent | null> {
    try {
      return await this.service.updateClickEvent({
        where: params,
        data: {
          ...data,

          gameSession: data.gameSession
            ? {
                connect: data.gameSession,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          clickTime: true,

          gameSession: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ClickEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClickEvent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClickEvent(
    @common.Param() params: ClickEventWhereUniqueInput
  ): Promise<ClickEvent | null> {
    try {
      return await this.service.deleteClickEvent({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          clickTime: true,

          gameSession: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
